title: "Jack Hamond | Civil Engineer"
description: "A portfolio showcasing my engineering projects and coding skills."
url: "https://jackhamondpro.github.io"
baseurl: ""
logo: "/assets/images/logo.png"
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
