title: "Jack Hamond | Civil Engineer"
description: "A portfolio showcasing my engineering projects and coding skills."
url: "https://jackhamondpro.github.io"
baseurl: ""
# logo: "/assets/images/logo.png"
theme: "minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-seo-tag
