title: "Jack Hamond | Engineering Technician"
description: "A portfolio showcasing my engineering projects and coding skills."
url: "https://jackhamondpro.github.io"
baseurl: ""
logo: "/assets/images/logo.jpg"
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed

feed:
  path: /feed.xml   # Path where the feed will be accessible

sass:
  style: compressed  # Optional, compresses the CSS

# Include custom styles in the head
include:
  - "_assets/css/style.scss"

navigation:
  - name: "Home"
    link: "/"
  - name: "About Me"
    link: "/about/"
  - name: "Projects"
    link: "/projects/"
      
